FROM node:14-alpine

WORKDIR /opt/project

COPY api/package*.json ./
RUN npm install
RUN npm install -g eslint

RUN apk add --no-cache bash

CMD [ -d "node_modules" ] && npm run start || npm ci -q && npm run start