FROM node:14-alpine

WORKDIR /opt/project

COPY api/package*.json ./
RUN yarn install

RUN npm install -g @nestjs/cli

RUN apk add --no-cache bash

CMD [ -d "node_modules" ] && yarn run start:dev || yarn install --frozen-lockfile && yarn run start:dev